name: Maven Build and Publish

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 # Updated to use potential future versions

    - name: Set up JDK 11
      uses: actions/setup-java@v3 # Updated to use potential future versions
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn clean install

    - name: Upload JAR file
      uses: actions/upload-artifact@v3 # Updated to use potential future versions
      with:
        name: todo-app-jar
        path: target/todo-app-1.0-SNAPSHOT.jar
